### ISSUE TITLE
Typescript 

### ISSUE THREAD

**Issue by dimitriskoslek** [acathur/exec#2]
Hello there and thank you for sharing this module!

I have been having this error:

```
error: TS2345 [ERROR]: Argument of type 'null' is not assignable to parameter of type 'Reader'.

const msg = process.stderr && removeTrailingLineBreak(decoder.decode(await Deno.readAll(process.stderr)))

at https://deno.land/x/execute/mod.ts:32:91
```

Not sure what's the problem, any ideas?

**Comment by dimitriskoslek** [comment]
Oh my bad, I just saw the closed issue saying I would have to target the v1.1.0 for this :)
Excuse me, I'm closing this I guess.

**Comment by acathur** [comment]
Duplicate of #1
